### ISSUE TITLE
Style shortcuts on `Style`

### ISSUE THREAD

**Issue by KennedyTedesco** [php-tui/php-tui#151]
Annoys me a bit (just a bit) to have to do this:

```php
BlockWidget::default()
    ->borders(Borders::ALL)
    ->style(
        Style::default()->fg(
            AnsiColor::Blue
        )->bg(
            AnsiColor::White
        )->addModifier(
            Modifier::BOLD
        )->addModifier(
            Modifier::ITALIC
        )
    )
    ->titles(Title::fromString('Styled block'))
    ->widget($paragraph);
```

Adding those shortcuts, we can cut this off to:

```php
BlockWidget::default()
    ->borders(Borders::ALL)
    ->style(Style::default()->blue()->onWhite()->bold()->italic())
    ->titles(Title::fromString('Styled block'))
    ->widget($paragraph);
```

Also, something personal: I prefer `Style::new()` (shorter) to `Style::default()`. But I get why the default is used here...

So, what are your thoughts on this?

**Comment by dantleech** [comment]
Looks good, I guess it's just adding the trait? Ratatui does this: `Style::default().fg(Color::Yellow)`

as for `default` vs `new` - `default` is from a Rust trait, but in anycase here:

- `Foo::default()`: _never has arguments_ and the object is valid.
- `Foo::new(...)`: requires (or maybe can require) arguments - it is basically the equivalent of `new Foo(...)`

There are a few classes with `new()` currently but I would refactor to remove it in it's current role.

I'm also slightly torn if we should be using static constructors at all for Widgets and Shapes.

**Comment by KennedyTedesco** [comment]
@dantleech Sadly the trait expects class to have a `patchStyle()` (which is enforced by `Styleable` interface).

```php
public function black(): self
{
    return $this->patchStyle(Style::default()->fg(AnsiColor::Black));
}
```

The `Style` class only has the `path()` method. It will be a bit odd to implement this interface there and create a new pathStyle there...

Unless we change `path()` to `patchStyle()` in `Style`, but it brings us a bit of redundancy in the name ...

About `Foo::default()` and `Foo::new()` looks sensible and correct to me. :+1: 

About static constructors in general, I really like them.

**Comment by dantleech** [comment]
I think it's probably fine `patchStyle`, Style is Stylable ... apparently :smile:
