### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by dantleech** [php-tui/php-tui#16]
Full screen on an X230 (1920x1080) I get around 5-7FPS while Ratatui renders the same at at a guestimate of at least 25FPS. Find out what the bottleneck is.

**Comment by dkarlovi** [comment]
Would Black fire help here? I can create a profile or ten. Just let me know what exactly to run.

**Comment by dantleech** [comment]
it probably would, but not sure exactly what to profile without diving in a bit.

I know that it _is_ slower than Ratatui, which is also expected (Rust vs PHP) but struggle to understand how my old laptop is only able to render a low resolution animated elephpant  at 1-4FPS.

**Comment by dkarlovi** [comment]
The one-off scripts are probably too short so they get skewed by Composer and other one-off things. Is there a way for me to run one of the demo things for say 5-10 secs and then exit? That will probably show hot paths the best.

**Comment by dkarlovi** [comment]
Demo map:
https://blackfire.io/profiles/79089d7f-d554-415b-9749-db66e438b55d/graph

**Comment by dkarlovi** [comment]
Seems the common thread is `PhpTui\Tui\Model\Buffer::setStyle` (called by `PhpTui\Tui\Widget\Block::renderBorders`) calling `PhpTui\Tui\Model\Cell::setStyle` and `PhpTui\Tui\Model\Position::toIndex` (via `PhpTui\Tui\Model\Buffer::get`) a lot.

**Comment by dkarlovi** [comment]
Looking at the code for `Area` and `Position`, it would benefit from #19 because you could then short circuit the calculations, do them once when / if stuff changes and then just return the precalculated values / booleans.

**Comment by dkarlovi** [comment]
@dantleech check the links above for Blackfire profiles. I can't profile images because Blackfire doesn't like the STDERR being taken over, I don't know what's that about.

**Comment by dantleech** [comment]
thanks, i'll get round to this one soon :)

**Comment by dantleech** [comment]
but what you say is a good case for immutability - Ratatui is mutable - and I'm a bit torn on if to switch to immutable objects or not. but it would make it easy to "cache" based on the object IDs I guess (also thinking about splitting out the "rendering" responsiblity from the widgets as that also makes things awkward)

**Comment by dkarlovi** [comment]
IMO being able to skip millions of method calls because you know for a fact a property didn't change would make all the difference, it then allows you to further optimize in many ways which can themselves be relatively costly assuming you cache the results too.

You'd probably be able to go up the call stack and short circuit there too until you're basically just sleeping each tick. 😃

**Comment by dkarlovi** [comment]
Just wanted to remind about these, I don't know how long Backfire keeps them around, IIRC 30 days? I'll not delete them, but they will, so check them before they expire.

I can always make new ones though so not a huge issue, more a FYI.

**Comment by dantleech** [comment]
cool thanks, I think https://github.com/php-tui/php-tui/issues/85 will fix the immediate "performance" issues. I'm using PHPBench _ Xdebug + Kcachegrind for profiling at the moment which might not be quite as good as BF but good enough for now.

closing this one.
