### ISSUE TITLE
Padding left/top/right/bottom

### ISSUE THREAD

**Issue by dantleech** [php-tui/php-tui#174]
It seems `Padding::{left(),right(),top(),bottom()` are not static constructors as with `horizontal` and `vertical`.

Is that intentional? cc @KennedyTedesco

**Comment by KennedyTedesco** [comment]
Yes, it is intentional. I thought about having them to mutate the state previously created by the static constructors. Ex:

```php
Padding::all(4)->left(2); // All 4, only left 2
Padding::none()->left(4); // Only left 4
```

But if you think it's a good idea, I can add static constructors for them while keeping those state mutators.

So, these will be the same:

```php
Padding::left(4);
Padding::none()->left(4); 
```

It's your call.

**Comment by dantleech** [comment]
well, to me it makes just as much sense to have `Padding::none()->vertical(2)` as `Padding::none()->left(2)` so they should either all be static constructors or none. I think I prefer static constructors.

**Comment by dantleech** [comment]
i think initializing at zero is good :+1:
