### ISSUE TITLE
Multi-width issues with `parse()`

### ISSUE THREAD

**Issue by dantleech** [php-tui/php-tui#190]
When using parse the output is corrupted:

![image](https://github.com/php-tui/php-tui/assets/530801/fa4ae25a-f1e3-4140-a281-37f3b604f927)

![image](https://github.com/php-tui/php-tui/assets/530801/5f10569c-1a36-49b5-8d37-c3dcac20c964)

When using standard Spans it works:

```
                    Span::fromString('Welcome to the 🐘 '),
                    Span::fromString('PHP-TUI')->white()->onBlue(),
                    Span::fromString(' demo application.')
```

![image](https://github.com/php-tui/php-tui/assets/530801/d707f647-625d-4e49-8f9a-f81caa50bdfb)

cc @KennedyTedesco probably just needs to use `mb_strwidth` somewhere instead of `mb_strlen`!?

**Comment by KennedyTedesco** [comment]
I'll take care of this tonight. :muscle:
