### ISSUE TITLE
Events are blocking infinitely on (Mac?!?)

### ISSUE THREAD

**Issue by AuroraYolo** [php-tui/php-tui#199]
![image](https://github.com/php-tui/php-tui/assets/20986749/999c68f9-a8ef-4d55-b3fa-0c3eae82ce40)

Can I keep the world map on the left dynamically updated?

**Comment by dantleech** [comment]
You would typically run a TUI application in an event loop and rebuild the model and defender the page on every "tick" so everything is "dynamically" updated. See the example/demo for a primitive example

**Comment by AuroraYolo** [comment]
Can you help me implement a simple demo?

**Comment by dantleech** [comment]
Which is .... raw .... but the basics are there.

**Comment by AuroraYolo** [comment]
OK, I'll try

**Comment by AuroraYolo** [comment]
I ran the command page to execute the demo and there was no output in the terminal.

```shell
 ./example/demo/bin/demo

```

![image](https://github.com/php-tui/php-tui/assets/20986749/e0176e15-095c-497a-bc9a-c790b0a02701)

**Comment by dantleech** [comment]
Which O/S do you use?

**Comment by AuroraYolo** [comment]
> Which O/S do you use?
MacOs

**Comment by dantleech** [comment]
Hm, can you debug to find out where it is getting stuck? My guess would be where it reads the events in App.php

**Comment by AuroraYolo** [comment]
I guess the problem is here 
```shell
php-tui/term/src/Reader/StreamReader.php:29
```
When I kill the process, the following data appears
![image](https://github.com/php-tui/php-tui/assets/20986749/64837c0d-c15c-487d-b797-1216e9487592)

**Comment by AuroraYolo** [comment]
> 我想问题就在这里
> 
> ```shell
> php-tui/term/src/Reader/StreamReader.php:29
> ```
> 
> 当我杀死进程时，出现以下数据 ![图像](https://private-user-images.githubusercontent.com/20986749/286872505-64837c0d-c15c-487d-b797-1216e9487592.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMzQ5NDQsIm5iZiI6MTcwMTMzNDY0NCwicGF0aCI6Ii8yMDk4Njc0OS8yODY4NzI1MDUtNjQ4MzdjMGQtYzE1Yy00ODdkLWI3OTctMTIxNmU5NDg3NTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDA4NTcyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNDc1YTlkZmFlMTcxOTY4ODczZmI5M2Q0ZTYyZGM1YjliYzQ3YjUzZTA5NDRmOWZhMzQ0MDViMmIyOGFiMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IkgrtmlLnFW9frd5JNsN84yOfmLkjaFSjUWylmFrc1k)

I took a look and there is a while infinite loop here.

**Comment by dantleech** [comment]
my guess is it's an infinite loop [here](https://github.com/php-tui/php-tui/blob/fdbe4387e946664c6f7967351733d204c97c8461/example/demo/src/App.php#L142) because [stream reader](https://github.com/php-tui/term/blob/816db08045b45d04e3ef8e20b12cebd962b0ca92/src/Reader/StreamReader.php#L30-L32) is NOT returning NULL. Can you check what the value of `$bytes` is in the infinite loop?

If it's an empty string try returning NULL if it is an empty string?

**Comment by dantleech** [comment]
can you try `composer update` to 0.3.3 ?

**Comment by AuroraYolo** [comment]
still the same
![image](https://github.com/php-tui/php-tui/assets/20986749/93cdf794-70e0-4448-afcb-2867eda46e70)

**Comment by dantleech** [comment]
either `stream_get_contents` is blocking, or it is an infinite loop. If it's an infinite loop can you see what the value of `$bytes` is in that infinite loop?

**Comment by AuroraYolo** [comment]
![image](https://github.com/php-tui/php-tui/assets/20986749/54dae950-13d5-4337-b392-a8675fa8643b)

**Comment by AuroraYolo** [comment]
I've tried disabling extensions and the same thing

**Comment by web-vovan** [comment]
Try using it before exiting the script
`$terminal->execute(Actions::disableMouseCapture());`
