### ISSUE TITLE
Paragraph: wrap is not used

### ISSUE THREAD

**Issue by dantleech** [php-tui/php-tui#202]
`Paragraph::wrap()` is not taken into account - also should/could this be an Enum?

Possibly related to #203 maybe it should be:

```
enum Wrap {
    case Word;         // break line on words
    case Character;  // break line on chars
    case None;         // do not break line (i.e. just truncate)
}
```

or should "overflow" be

**Comment by dantleech** [comment]
it's also a weird implementation in Rust, `Wrap` is a optional struct when it could be en enum `enum Wrap { None; Word(bool); }`.

 I might consider something like:

```
enum Break {
    case None;   // text would just "overflow" and not wrap
    case Word;   // break on word
    case WordTrimmed; // break "trim: true"
    case Character; // what currently happens with `None`
}
```

**Comment by KennedyTedesco** [comment]
I've run various tests in ratatui, and changing trim from `true` to `false` doesn't change anything, lol. Just some specific texts and constructions.

About this Enum, it looks good. Now I get the `Character` case, just in case the user gets confused if he sees only `Word` (and he probably doesn't know that `None` does the char breaking by default).

If you don't mind, I can work on this next few days.

**Comment by dantleech** [comment]
Sure!
