### ISSUE TITLE
[Question] Symfony command wrapper

### ISSUE THREAD

**Issue by ellisgl** [php-tui/php-tui#224]
Has anyone tried using this to enhance the Symfony command output?

**Comment by dantleech** [comment]
You can use it in Symfony, it will not use the OutputInterface though, but that's fine?

**Comment by ellisgl** [comment]
I'll have to give that a try. Guess was thinking to deep, lol

**Comment by ellisgl** [comment]
Totally works in a command, without using the output interface.
