### ISSUE TITLE
Performance: Redraw policy

### ISSUE THREAD

**Issue by dantleech** [php-tui/php-tui#85]
Currently widgets and shapes "render" on every iteration. The buffer will only draw the _diff_ to the terminal, but the CPU cycles are always there, and some widgets are expensive to compute (e.g. image).

We can avoid redrawing widgets if we can easily tell if the widget's state has changed.

- some widgets are "pure": the rendered output is 100% based on the state of the widget.
- ...but others are impure: e.g. the widget _state_ may be unchanged but f.e. it could be pulling data from an external source at "render time" (e.g. a database or webservice)

We can add a "redraw" policy to the Widgets:

- `Redraw::ALWAYS()`: Redraw on every iteration.
- `Redraw::TTL(10)`: Redraw after timeout (or on invalidation, e.g. screen resize)
- `Redraw::KEY()`: Redraw based on a state "key" provided by the widget.

The mechanism itself can either act as a:

- `cache`: The Grid widget can cache the rendered area for each widget.
- `cell property`: We can indicate that the cell in the widgets "range" should not be updated. Ratatui has a similar concept used for a different purpose (I think) [skip](https://github.com/ratatui-org/ratatui/blob/9f371000968044e09545d66068c4ed4ea4b35d8a/src/buffer.rs#L88)

Probably it's better to mark the cell to be "skipped" as this could potentially also work at a lower level than the Grid widget.

**Comment by KennedyTedesco** [comment]
Awesome! A common pattern I see is marking a cell as dirty when its state changes (probably the same idea as this skip). Looking forward to seeing this improvement. 🚀

**Comment by dantleech** [comment]
I'm going to drop this for now... adding any caching is going to be complicated and bugful. If you want to run full-screen animations it won't save you anyway :D

**Comment by KennedyTedesco** [comment]
:+1:  "We're trying" to get a bit closer to the Rust performance, but maybe it will never happen, hard to say that haha I'm going to test against php-src master, which has a new JIT Engine to see if has any kind of benefit (at least for the computational part, because the I/O (streams) will not have any difference).
